# -*- coding: utf-8 -*-
"""Elavarasu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kHnrkpyVg-BpsK0f-7qcPOZLdfWHA9Tl
"""

print("I am signing up for Replit&#39;s 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I&#39;ll be usingReplit, an amazing online IDE so I can do this from my phone wherever I happend to be.No excuses for not coding from the middle of a field!")

dict={}

mobile cost = 12300

import pandas as pd
student_data=pd.DataFrame({"Student_Name": ["Ragul", "jackey", "duri", "Kavi", "Yogesh", "Guhan", "Bharath", "Guru", "Pravin", "Manoj"],
     "Age": [20,20,20,20,20,20,20,20,20,20],
     "DOB(year)": [2001,2001,2001,2001,2001,2001,2001,2001,2001,2001],
     "Weight(kg)" : [60,62,75,80,49,67,83,66,73,72],
     "Height(cm)" : [150,120,135,177,156,188,199,154,177,133]})

student_data["BMI"]=student_data["Weight(kg)"]/student_data["Height(cm)"]*student_data["Height(cm)"]

student_data["Status"]=student_data["BMI"].apply(lambda x: "Normal" if x>50 and x<80 else "Underweight")
 print(student_data)

print("\t\t\tcalculating EB bill")
type=int(input("\n select the residntial palce:\n\n1.household\n2.commercial\n"))
if(type ==1):
  def house():
    print("EB Bill for your House:")
    
    unit=int(input("enter the units:"))
    if(unit<=100):
        ui=unit*0.50
    elif unit>=101 and unit<200:
         ui=unit*0.75
    elif unit<201 and unit<300:
         ui=unit*1.20
    elif unit>300:
         ui=unit*1.50    
    
    print("total charges:",ui)
  house()  
if(type ==2):
     def com():
      print("EB Bill for your Commercial palce:")
   
     unit=int(input("enter the units:"))
     if (unit<=100):
        ui=unit*0.50
     elif unit>=101 and unit<200:
         ui=unit*0.75
     elif unit<201 and unit<300:
         ui=unit*1.20
     elif unit>300:
         ui=unit*1.50    
    
     print("total charges:",ui)
     com()